name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: |
          g++ -std=c++23 -Wall -Wextra -O2 -o redblacktree main.cpp

      - name: Run tests
        run: ./redblacktree
