name: Build/Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Test URL Encoding
      run: |
        branch_name="feature/my-branch#123"
        ENCODED_BRANCH_NAME=$(printf %s "$branch_name" | jq -sRr @uri)
        echo "Original Branch Name: $branch_name"
        echo "Encoded Branch Name: $ENCODED_BRANCH_NAME"
